from __future__ import annotations

DOC_TYPE_TO_GROUP: dict[str, str] = {
    "NQ": "A",
    "QĐ": "A",
    "CT": "A",
    "QC": "A",
    "QYĐ": "A",
    "TB": "B",
    "HD": "B",
    "CTr": "B",
    "KH": "B",
    "PA": "B",
    "ĐA": "B",
    "DA": "B",
    "BC": "B",
    "TTr": "B",
    "CĐ": "B",
    "CV": "B",
    "BB": "C",
    "HĐ": "C",
    "BGN": "C",
    "BTT": "C",
    "GUQ": "D",
    "GM": "D",
    "GGT": "D",
    "GNP": "D",
    "PG": "D",
    "PC": "D",
    "PB": "D",
    "TCg": "D",
    "UNKNOWN": "E",
}

GROUP_SCHEMAS: dict[str, tuple[str, ...]] = {
    "A": (
        "header",
        "legal_basis",
        "promulgation",
        "chapter",
        "article",
        "clause",
        "point",
        "implementation",
        "recipient_signature",
        "appendix",
    ),
    "B": (
        "header",
        "recipient",
        "context",
        "objective",
        "requirement",
        "content",
        "task",
        "timeline",
        "budget",
        "recommendation",
        "conclusion",
        "signature",
        "appendix",
    ),
    "C": (
        "header",
        "time_location",
        "participants",
        "party_a",
        "party_b",
        "article",
        "content",
        "table_items",
        "payment_terms",
        "handover_items",
        "conclusion",
        "signature_parties",
    ),
    "D": ("single_doc_chunk", "field_metadata", "signature"),
    "E": (
        "page_chunk",
        "paragraph_chunk",
        "heading_candidate_chunk",
        "table_candidate_chunk",
        "signature_candidate_chunk",
    ),
}

DOC_TYPE_PATTERNS: tuple[tuple[str, str, float], ...] = (
    ("QĐ", r"\bquyet\s+dinh\b", 0.94),
    ("NQ", r"\bnghi\s+quyet\b", 0.92),
    ("CT", r"\bchi\s+thi\b", 0.90),
    ("QC", r"\bquy\s+che\b", 0.90),
    ("QYĐ", r"\bquy\s+dinh\b", 0.90),
    ("TB", r"\bthong\s+bao\b", 0.90),
    ("HD", r"\bhuong\s+dan\b", 0.90),
    ("CV", r"\bcong\s+van\b|\bv\s*/\s*v\b|\bkinh\s+gui\b", 0.86),
    ("CTr", r"\bchuong\s+trinh\b", 0.89),
    ("KH", r"\bke\s+hoach\b", 0.91),
    ("PA", r"\bphuong\s+an\b", 0.89),
    ("ĐA", r"\bde\s+an\b", 0.89),
    ("DA", r"\bdu\s+an\b", 0.87),
    ("BC", r"\bbao\s+cao\b", 0.89),
    ("BB", r"\bbien\s+ban\b", 0.91),
    ("TTr", r"\bto\s+trinh\b", 0.90),
    ("HĐ", r"\bhop\s+dong\b", 0.92),
    ("CĐ", r"\bcong\s+dien\b", 0.89),
    ("BGN", r"\bban\s+ghi\s+nho\b", 0.88),
    ("BTT", r"\bban\s+thoa\s+thuan\b", 0.88),
    ("GUQ", r"\bgiay\s+uy\s+quyen\b|\bnguoi\s+uy\s+quyen\b", 0.90),
    ("GM", r"\bgiay\s+moi\b|\btran\s+trong\s+kinh\s+moi\b", 0.90),
    ("GGT", r"\bgiay\s+gioi\s+thieu\b|\bgioi\s+thieu\s+ong\s*/?\s*ba\b", 0.89),
    ("GNP", r"\bgiay\s+nghi\s+phep\b|\bnghi\s+tu\s+ngay\b", 0.89),
    ("PG", r"\bphieu\s+gui\b", 0.86),
    ("PC", r"\bphieu\s+chi\b|\bphieu\s+chuyen\b|\bnguoi\s+nhan\s+tien\b", 0.86),
    ("PB", r"\bphieu\s+bao\b", 0.86),
    ("TCg", r"\bthu\s+cong\b", 0.84),
)

FUZZY_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    (r"\b(?:Diều|Đlều|Dỉều)\b", "Điều"),
    (r"\bQuyet\s+dinh\b", "Quyết định"),
    (r"\bNoi\s+nhan\b", "Nơi nhận"),
    (r"\bKinh\s+gui\b", "Kính gửi"),
    (r"\bV\s*/?\s*v\b", "V/v"),
    (r"\bBen\s+A\b", "Bên A"),
    (r"\bBen\s+B\b", "Bên B"),
)
